executable = wrapper.sh
arguments = 
x509userproxy = /afs/cern.ch/user/c/cbasile/X509_USER_PROXY
use_x509userproxy = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = condor_test/, job.out, job.err, job.log
output_destination = root://eosuser.cern.ch//eos/user/c/cbasile/HLT_DoubleMu/CMSSW_14_0_5/src/myAnalyzers/bph-hlt-tools/Efficiency_v2/results2022_v4/
transfer_input_files = /afs/cern.ch/user/c/cbasile/X509_USER_PROXY, ../utils.py, ../config.py, ../cutNcount_efficiency.py, ../data/tagtuples_HLT_Mu8_v_MC_Jpsito2Mu_pythia8_2022EE_v4.json, ../selection/mediumID_selection_L1.json, wrapper.sh
output = job.out
error = job.err
log = job.log
request_cpus = 1
request_memory = 1GB
request_disk = 1GB
getenv = True

queue 1